name: storage

services:
  minio:
    build:
      context: ./server/Minio
      dockerfile: Dockerfile
    image: minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PROMETHEUS_AUTH_TYPE=${MINIO_PROMETHEUS_AUTH_TYPE}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - proxy
      - stornet
    labels:
      - "traefik.enable=true"
      # Route /minio -> MinIO S3 API (HTTP)
      - "traefik.http.routers.minio.rule=PathPrefix(`/minio`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.middlewares=minio-strip"
      - "traefik.http.middlewares.minio-strip.stripprefix.prefixes=/minio"
      - "traefik.http.services.minio.loadbalancer.server.port=${MINIO_PATH_LOADBALENCER_SERVER_PORT}"
      - "traefik.http.routers.minio.priority=100"
      # Route rule -> Minio (HTTP)
      - "traefik.http.routers.minio-storage.rule=Host(`storage.${HOST}`)"
      - "traefik.http.routers.minio-storage.entrypoints=web"
      - "traefik.http.routers.minio-storage.priority=2"
      - "traefik.http.routers.minio-storage.service=minio-storage"
      - "traefik.http.services.minio-storage.loadbalancer.server.port=${MINIO_STORAGE_LOADBALENCER_SERVER_PORT}"
      # Network
      - "traefik.docker.network=proxy"

  redis:
    build:
      context: ./server/Redis
      dockerfile: Dockerfile
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - proxy
      - cachenet
    restart: unless-stopped
    # No Traefik labels here: Redis is TCP on 6379 (not HTTP). Keep it internal.

  # LEAVE IT COMMENTED IF YOU DON'T NEED IT
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   restart: unless-stopped
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379:0:changeme
  #     - HTTP_USER=admin
  #     - HTTP_PASSWORD=secret
  #     # Make the app aware it is served under /redis-commander
  #     - URL_PREFIX=/redis-commander
  #     - HTTP_PATH=/redis-commander
  #   labels:
  #     - "traefik.enable=true"
  #     # Route /redis-commander -> Redis Commander Web UI (HTTP)
  #     - "traefik.http.routers.rediscommander.rule=PathPrefix(`/redis-commander`)"
  #     - "traefik.http.routers.rediscommander.entrypoints=web"
  #     - "traefik.http.routers.rediscommander.service=rediscommander"
  #     # Ensure "/redis-commander" (without trailing slash) redirects to "/redis-commander/"
  #     - "traefik.http.routers.rediscommander.middlewares=rediscommander-slash"
  #     - "traefik.http.middlewares.rediscommander-slash.redirectregex.regex=^/redis-commander$"
  #     - "traefik.http.middlewares.rediscommander-slash.redirectregex.replacement=/redis-commander/"
  #     - "traefik.http.services.rediscommander.loadbalancer.server.port=8081"
  #     - "traefik.docker.network=proxy"
  #   networks:
  #     - cachenet
  #     - proxy

volumes:
  redis_data:
  minio_data:

networks:
  proxy:
    name: proxy
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  dbnet:
    name: dbnet
    ipam:
      driver: default
      config:
        - subnet: 172.31.10.0/24
  cachenet:
    name: cachenet
    ipam:
      driver: default
      config:
        - subnet: 172.31.20.0/24
  stornet:
    name: stornet
    ipam:
      driver: default
      config:
        - subnet: 172.31.30.0/24