name: security

services:
  # Identity Provider - Keycloak (Quarkus)
  keycloak:
    build:
      context: ./server/Keycloak
      dockerfile: Dockerfile
    image: keycloak:dev
    container_name: keycloak
    environment:
      KC_HTTP_ENABLED: "${KC_HTTP_ENABLED}"
      # Database via ProxySQL on dbnet
      KC_DB: ${KC_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
      # Admin bootstrap (dev only; move to secrets later)
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      # Reverse proxy awareness
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_PROXY: ${KC_PROXY}
      KC_HOSTNAME_STRICT: "${KC_HOSTNAME_STRICT}"
      # KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_METRICS_ENABLED: "${KC_METRICS_ENABLED}"
      KC_HEALTH_ENABLED: "${KC_HEALTH_ENABLED}"
      # OpenTelemetry traces -> OTel Collector -> Tempo
      KC_FEATURES: ${KC_FEATURES}
      KC_OPENTELEMETRY_ENDPOINT: ${KC_OPENTELEMETRY_ENDPOINT}
      KC_OPENTELEMETRY_PROTOCOL: ${KC_OPENTELEMETRY_PROTOCOL}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.${HOST}`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=${KC_LOADBALENCER_SERVER_PORT}"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.routers.keycloak.priority=100"
      - "traefik.docker.network=proxy"
    command: ["start"]
    networks:
      - proxy
      - dbnet
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
      
volumes:
  keycloak_data:

networks:
  proxy:
    name: proxy
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  dbnet:
    name: dbnet
    ipam:
      driver: default
      config:
        - subnet: 172.31.10.0/24
  cachenet:
    name: cachenet
    ipam:
      driver: default
      config:
        - subnet: 172.31.20.0/24
  stornet:
    name: stornet
    ipam:
      driver: default
      config:
        - subnet: 172.31.30.0/24