name: CI/CD/DEVOPS

services:
  jenkins:
    container_name: jenkins
    build:
      context: ./server/jenkins
      dockerfile: Dockerfile
    image: jenkins-lts:latest
    ports:
      - "${JENKINS_AGENT_PORT}:50000"
    environment:
      - TZ=${TZ}
      - HOST=${HOST}
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc_configs/jenkins.yaml
      # OIDC client secret is fetched automatically at startup if not provided
      # - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      # Keycloak bootstrap for auto-fetching the Jenkins client secret
      - JENKINS_URL=${JENKINS_URL}
      - KC_URL=${KC_URL}
      - KC_REALM=internal
      - KC_ADMIN_USER=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - OIDC_CLIENT_ID=jenkins
      - JAVA_OPTS=${JAVA_OPTS}
    volumes:
      - ./server/jenkins/data:/var/jenkins_home
    restart: unless-stopped
    extra_hosts:
      - "auth.${HOST}:host-gateway"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${HOST}`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=${JENKINS_HTTP_PORT}"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.priority=100"
      - "traefik.docker.network=proxy"

volumes:
  jenkins_home:

networks:
  proxy:
    external: true
