name: messaging

services:
  # TURN/STUN server (coturn)
  turn:
    build:
      context: ./server/Turn
      dockerfile: Dockerfile
    image: turn:latest
    container_name: turn
    ports:
      - "3478:3478/udp"
      - "3478:3478"
      - "49160-49200:49160-49200/udp"
    restart: unless-stopped
    volumes:
      - turn_data:/var/lib/turn
    networks:
      - proxy

volumes:
  turn_data:

networks:
  proxy:
    name: proxy
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  dbnet:
    name: dbnet
    ipam:
      driver: default
      config:
        - subnet: 172.31.10.0/24
  cachenet:
    name: cachenet
    ipam:
      driver: default
      config:
        - subnet: 172.31.20.0/24
  stornet:
    name: stornet
    ipam:
      driver: default
      config:
        - subnet: 172.31.30.0/24