apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1
  - name: Postgres Cluster (RO)
    orgId: 1
  - name: Postgres Keycloak (RO)
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - service.name

  - name: Postgres Cluster (RO)
    uid: postgresql
    type: postgres
    access: proxy
    url: haproxy:5432
    user: postgres
    database: postgres
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: postgres

  - name: Postgres Keycloak (RO)
    uid: postgresql_keycloak
    type: ${KC_DB_TYPE}
    access: proxy
    url: postgres-keycloak:5432
    user: ${KC_DB_USERNAME}
    database: ${KC_DB_NAME}
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${KC_DB_PASSWORD}