{
 "title": "Traefik - Overview",
 "tags": [ "traefik" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"traefik\"})"
    }
   ]
  },
  {
   "title": "Latency p95 (seconds) - Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(traefik_service_request_duration_seconds_bucket{job=\"traefik\"}[5m])))"
    }
   ]
  },
  {
   "title": "Service Requests (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (service)(rate(traefik_service_requests_total{job=\"traefik\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests by Code (Entrypoints)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code)(rate(traefik_entrypoint_requests_total{job=\"traefik\"}[5m]))"
    }
   ]
  }
 ]
}