global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'haproxy_exporter'
    static_configs:
      - targets: ['haproxy_exporter:9101']

  - job_name: 'etcd'
    metrics_path: /metrics
    static_configs:
      - targets: ['etcd1:2379', 'etcd2:2379', 'etcd3:2379']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

# Add more scrape jobs as needed, e.g., per-patroni node exporters later

  - job_name: 'keycloak'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:9100']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
